### PR TITLE
[irods/irods#7265] post-4.3.1 CMake touch-ups

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Looks good.

Pound when ready.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by SwooshyCueb** [comment]
Actually, hold off on merging this. I just noticed something I missed

**Comment by SwooshyCueb** [comment]
Should be good to merge now

**Pull request merged**
